//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GPGameProto.proto
// Note: requires additional types generated from: GameBase.proto
namespace Proto.GPGameProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GPCMD_ReqStartGame")]
  public partial class GPCMD_ReqStartGame : global::ProtoBuf.IExtensible
  {
    public GPCMD_ReqStartGame() {}
    
    private uint _roomid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GPCMD_RespStartGame")]
  public partial class GPCMD_RespStartGame : global::ProtoBuf.IExtensible
  {
    public GPCMD_RespStartGame() {}
    
    private readonly global::System.Collections.Generic.List<Proto.GameBase.GameUserInfo> _gameUser = new global::System.Collections.Generic.List<Proto.GameBase.GameUserInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"gameUser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.GameBase.GameUserInfo> gameUser
    {
      get { return _gameUser; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GPCMD_PlayerInfo")]
  public partial class GPCMD_PlayerInfo : global::ProtoBuf.IExtensible
  {
    public GPCMD_PlayerInfo() {}
    
    private uint _seat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GPCMD_UpdatePlayerState")]
  public partial class GPCMD_UpdatePlayerState : global::ProtoBuf.IExtensible
  {
    public GPCMD_UpdatePlayerState() {}
    
    private uint _seat;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private uint _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GPCMD_UpdateStep")]
  public partial class GPCMD_UpdateStep : global::ProtoBuf.IExtensible
  {
    public GPCMD_UpdateStep() {}
    
    private uint _step;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint step
    {
      get { return _step; }
      set { _step = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GPGameCMD")]
    public enum GPGameCMD
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GAME_REQSTARTGAME", Value=1)]
      CMD_GAME_REQSTARTGAME = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GAME_RESPSTARTGAME", Value=2)]
      CMD_GAME_RESPSTARTGAME = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GAME_PLAYERINFO", Value=3)]
      CMD_GAME_PLAYERINFO = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GAME_UPDATEPLAYERSTATE", Value=4)]
      CMD_GAME_UPDATEPLAYERSTATE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_GAME_UPDATESTEP", Value=5)]
      CMD_GAME_UPDATESTEP = 5
    }
  
}