//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserProto.proto
// Note: requires additional types generated from: RoomBase.proto
namespace Proto.UserProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqCreateUser")]
  public partial class ReqCreateUser : global::ProtoBuf.IExtensible
  {
    public ReqCreateUser() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespCreateUser")]
  public partial class RespCreateUser : global::ProtoBuf.IExtensible
  {
    public RespCreateUser() {}
    
    private Proto.RoomBase.FlagMsg _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RoomBase.FlagMsg data
    {
      get { return _data; }
      set { _data = value; }
    }
    private Proto.RoomBase.UserInfo _userinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RoomBase.UserInfo userinfo
    {
      get { return _userinfo; }
      set { _userinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReqGetUser")]
  public partial class ReqGetUser : global::ProtoBuf.IExtensible
  {
    public ReqGetUser() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RespGetUser")]
  public partial class RespGetUser : global::ProtoBuf.IExtensible
  {
    public RespGetUser() {}
    
    private Proto.RoomBase.FlagMsg _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RoomBase.FlagMsg data
    {
      get { return _data; }
      set { _data = value; }
    }
    private Proto.RoomBase.UserInfo _userinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RoomBase.UserInfo userinfo
    {
      get { return _userinfo; }
      set { _userinfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}